{
 "title": "Gravitech",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CAT Telecom",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "content": "<br><center><bgColor\": \"#111122\"><img src=\"https://www.cattelecom.com/uploads/images/800px-CATTelecom_Logo.png\" width=\"170\" alt=\"CAT Telecom\">"
  },
  { "title": "Date / Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 } },
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "celsius",
   "targets": [
    {
     "measurement": "collectd",
     "select": [
      [
       { "params": [ "Sensor1" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "humidity",
   "targets": [
    {
     "measurement": "collectd",
     "select": [
      [
       { "params": [ "Sensor2" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "temperature (°C)",
     "measurement": "collectd",
     "query": "SELECT \"sensor1\" FROM \"gravitech\" WHERE (\"DevAddr\" = '89EFFA01') AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor1" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max T",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "celsius",
   "valueName": "max",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"sensor1\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor1" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min T",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "celsius",
   "valueName": "min",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"sensor1\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor1" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max H",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "humidity",
   "valueName": "max",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"sensor2\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min H",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "humidity",
   "valueName": "min",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"sensor2\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Humidity (%H)",
     "measurement": "collectd",
     "query": "SELECT \"sensor1\" FROM \"gravitech\" WHERE (\"DevAddr\" = '89EFFA01') AND $timeFilter",
     "select": [
      [
       { "params": [ "Sensor2" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "format": "dBm",
   "valueName": "current",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"LrrRSSI\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/",
     "select": [
      [
       { "params": [ "LrrRSSI" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"LrrSNR\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/",
     "select": [
      [
       { "params": [ "LrrSNR" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SF",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"LrrSNR\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/",
     "select": [
      [
       { "params": [ "LSpFact" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Payload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "collectd",
     "query": "SELECT \"Lrrid\" FROM \"gravitech\" WHERE \"DevAddr\" =~ /$devAddr/",
     "select": [
      [
       { "params": [ "Payload" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gravitech board",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "collectd",
     "select": [
      [
       { "params": [ "Sensor1" ], "type": "field" }
      ],
      [
       { "params": [ "Sensor2" ], "type": "field" }
      ],
      [
       { "params": [ "LrrRSSI" ], "type": "field" }
      ],
      [
       { "params": [ "LrrSNR" ], "type": "field" }
      ],
      [
       { "params": [ "Payload" ], "type": "field" }
      ],
      [
       { "params": [ "FCntUp" ], "type": "field" }
      ],
      [
       { "params": [ "LSpFact" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}